// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:recipes_app/features/recipes/domain/entities/ingredient_hive_model.dart';
import 'package:recipes_app/features/recipes/domain/entities/recipe_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(IngredientHiveModelAdapter());
    registerAdapter(RecipeHiveModelAdapter());
  }
}
